### ISSUE TITLE
User study Design

### ISSUE THREAD

**Issue by curtomil** [amyxzhang/wikum#106]
### Issue 

Plan a user study of the use of Wikum by Decide Madrid users.

### Proposal (if more, please edit them in)

User study design should define the following:
* Objectives of the study
* Conditions of the study
* Questions to ask participants (Questions and tools for observations should be classified by area/domains of intervention) 
* Requirements for ethical research (consent sheet, informing participant of process, their rights to interrupt, etc.)
* How to record use
* Write study conclusions

### Outcome

Setting up user study design: https://docs.google.com/document/d/1sHHqY-eRjwNGRhiJwYC5xSuO0B6aQrIlQrFUMXi1aFU/edit

### Example

Are there good examples of user studies to base ours on?

### Engagement
Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by amyxzhang** [comment]
User study of Wikum: http://people.csail.mit.edu/axz/papers/wikum.pdf
It was a lab study which is quite different from what we are planning this time around.
Lab studies emphasize keeping as many parts of the environment constant and testing carefully a few settings or experimental vs control. This means lab studies are usually quite "unrealistic".

**Comment by amyxzhang** [comment]
Very good overview of user studies and things to watch out for/be aware of:
http://web.mit.edu/6.813/www/sp17/classes/11-user-testing/

**Comment by RamlAyadi** [comment]
Could be this a begin to start defining area of research? 
<img src="https://scontent.fmad3-8.fna.fbcdn.net/v/t34.0-0/p280x280/23416322_773403716177430_1125411182_n.jpg?oh=c813bda60629b442e9a5727c169f2526&oe=5A06102A" alt="Screenshot 1" height="200px"/>

**Comment by amyxzhang** [comment]
I rescoped this issue to just be about user study design, otherwise it's too large. Since we have finished design, I'm going to close this.
