### ISSUE TITLE
Presentation for ICDemocracia

### ISSUE THREAD

**Issue by amyxzhang** [amyxzhang/wikum#109]
### Issue 

Plan and create presentation for end of ICDemocracia

### Proposal (if more, please edit them in)

Plan and create presentation (can be slides, demo, etc.) of the outcome of our work.

Also talk about the process!

### Outcome

Presentation

### Engagement
Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by BereZambrano** [comment]
Great! I'm a little worry about this.

Maybe we can structure it like: 1: the general stage of wikum when it arrives to medialab and 2: a short story-telling of the process highlighting how we improve it while we were here.
