### ISSUE TITLE
Plan and Conduct Recruitment for User Study

### ISSUE THREAD

**Issue by amyxzhang** [amyxzhang/wikum#111]
### Issue 

Need to plan user study recruitment

### Proposal (if more, please edit them in)

Plan and conduct recruitment for user study

### Outcome

emails sent

### Engagement
Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by curtomil** [comment]
https://docs.google.com/forms/u/0/d/1HmuQbO_OnVdoIkxe7Z5A4aNzeXbkSWis-nG1XUY4aoA/edit?ntd=1&usp=forms_home&ths=true

Google form for survey
