### ISSUE TITLE
Require confirmation for "Delete summary node" action

### ISSUE THREAD

**Issue by jtmorgan** [amyxzhang/wikum#30]
As a user who puts lots of time and energy into my summaries, I don't want to delete them by mistake! Perhaps you can require an explicit confirmation step when a user deletes a summary (or performs any other destructive action). 

It might also be useful to place the "delete summary node" farther from the other, non-destructive options. Notice when you compose a new email in Gmail, "send" and "discard draft" are on different sides of the toolbar.

**Comment by amyxzhang** [comment]
Done.
