### ISSUE TITLE
Only display valid options in thread tree contextual menu

### ISSUE THREAD

**Issue by jtmorgan** [amyxzhang/wikum#37]
Similar to [issue 35](https://github.com/amyxzhang/wikum/issues/35), but not about toggle elements per se.

When you hover over any parent comment in the thread tree, you see a contexual menu with the following options: collapse replies, expand replies, isolate subtree, and expand all summaries. You see the same four options whether or not the replies have already been expanded, and whether or not there are any summary-node children in the thread. 

This can be confusing. It would be better to only show the user valid options. For example, if the reply subtree is already fully expanded, then remove the option to "expand replies". Similarly, if there are no summary nodes in the child subtree, don't display the "expand all summaries" option.

**Comment by amyxzhang** [comment]
Also, there should be the option to do the converse of "expand all summaries" which is "collapse all summaries" if it is expanded.

**Comment by amyxzhang** [comment]
Done.
