### ISSUE TITLE
Design Comparison with Alternative or Similar Systems

### ISSUE THREAD

**Issue by amyxzhang** [amyxzhang/wikum#83]
### Issue 

As a developer who is going to collaborate in the improvement of WIKUM source code, I found that WIKUM

1. is unclear on how it is different from other tools
2. could learn from other tools

### Proposal

Research other systems and consider:
- how Wikum is different/fills a different need
- what design takeaways we can use

Examples:
- ConsiderIt
- Kialo
- Pol.is
- Assembl
- Loomio
- DemocracyOS
- Quora
- StackExchange
- Discourse
- Arguman

### Outcome

Output: 

Google Doc notes https://docs.google.com/document/d/1u_y3Y7mSzmw-pQk_YktvmX1hGZH1Tmh_bYOEXei_-sI/edit?usp=sharing

Summarising slides: https://docs.google.com/presentation/d/11Ep0hfjYtN7DUsgOlkaxBLgNZ_S9ifdCQo3poIuTPk0/edit#slide=id.g2aa8a67759_0_77

### Engagement
Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by amyxzhang** [comment]
There are also some parallels to collaborative document editors such as Google Docs.

**Comment by amyxzhang** [comment]
Someone pointed me to Assembl: assembl.bluenove.com/en/

**Comment by abhicodebase** [comment]
It needs to be complemented by documentation team.

**Comment by curtomil** [comment]
Here's a link with a start to the document

https://docs.google.com/document/d/1u_y3Y7mSzmw-pQk_YktvmX1hGZH1Tmh_bYOEXei_-sI/edit?usp=sharing

**Comment by abhicodebase** [comment]
set of parameters / template for comparison , that can be extended for future tools too .

**Comment by curtomil** [comment]
@amyxzhang @julioremo Can you guys have a look? Do you think we should add something? Explore different issues?

**Comment by amyxzhang** [comment]
consider possibly discourse.org, loomio.org

**Comment by curtomil** [comment]
Added slides to OP

**Comment by amyxzhang** [comment]
Closing this!
