### ISSUE TITLE
Research Open Democracy Organizational Needs ( Stakeholder Maps ) 

### ISSUE THREAD

**Issue by amyxzhang** [amyxzhang/wikum#84]
Talk to people at the workshop or outside connections who has needs related to facilitating large-scale dialogue.
Come up with a list of questions to ask.
Some ideas:
- What scale of discussion would you like to support? How many participants do you have now vs how many you would like to have?
- What problems have you encountered related to facilitating quality discussions?
- What needs do you have in a discussion system?
- What happens after the discussion is over?
- What system do you use and what format is your discussion data?
- Is your data public? How easy is it to connect to get your data programmatically?
- Ask if we can see example discussions/if we can use their data to import into Wikum.
Perhaps record interviews?

**Comment by amyxzhang** [comment]
We should talk to Consul/look at Consul to see if Wikum could be an extension of it.

**Comment by elaragon** [comment]
I agree, data from discussions in debates and proposals are accesible via API: https://github.com/amiedes/consul/blob/1754-api-docs/doc/api/api_es.md

**Comment by amyxzhang** [comment]
I am going to close this because it overlaps with #87
