### ISSUE TITLE
Stakeholders maps and users profils and needs : Identifying essentials functions to develop possible adjustments

### ISSUE THREAD

**Issue by RamlAyadi** [amyxzhang/wikum#87]
This issue is under consideration for the creation of WIKUM documentation
(Texto en español abajo)
### Stakeholders interest and users profils and needs

As a designer to improve the use of the plataforme 

1. Many questions: who are the users? can we categorize them on "specific profils" /personas? how do they behave/use Wikum? and what are them needs in term of use?
2. It's hard to rise awarness to participatory debates
3. Ergonomic and lisible interfaces 

### Proposal

A stakeholderg mapping will be usefull to think any issue. 
Users profiling and experiences  (shadowing the uses/analysing some behavior/interviewing) will help us identify ways to improve the interface and its use

Outcame: 
Users Profiles (map and Doc)
Stakeholders map (map and Doc)
Conclusions about users needs. (Doc)

**Google doc ** https://docs.google.com/document/d/1yLC9jSjDyvfG2Pmc3bAsthEJuHMCewc5J3TJXBib1zg/edit?ts=5a042fba

### Engagement
Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

--------------------------------------------------------------------------------------------

### Asunto

Como diseñadora que colaborara en el mejoramiento de la plataforma encuentro las siguientes puntos:

1. Podemos organizar/categorizar  a los usuarios de WIKUM según su perfil o área de experiencia?
2. Segundo
3.  Tercero

Info adicional: https://docs.google.com/document/d/1yLC9jSjDyvfG2Pmc3bAsthEJuHMCewc5J3TJXBib1zg/edit?usp=sharing

### Propuesta

Texto explicando la propuesta

* Primero
* Segundo

### Ejemplo propuesto

**Comment by amyxzhang** [comment]
Copying short brainstorm of questions to ask in duplicate issue #84:

Talk to people at the workshop or outside connections who has needs related to facilitating large-scale dialogue.
*we should talk to the people in Consul/Decide*

Some ideas for questions to ask:

What scale of discussion would you like to support? How many participants do you have now vs how many you would like to have?
What problems have you encountered related to facilitating quality discussions?
What needs do you have in a discussion system?
What happens after the discussion is over?
What system do you use and what format is your discussion data?
Is your data public? How easy is it to connect to get your data programmatically?
Ask if we can see example discussions/if we can use their data to import into Wikum.
Perhaps record interviews?

**Comment by RamlAyadi** [comment]
So we can identify people to ask, we have:
    -People with same experiences ( Consul/decide madrid) (learn from other expériences).
    -People with potential interest to use Vikum(leran what could be their expectations - maybe create new functions).
    -People like average users (to analyse them behavior to improve wikum use)
    ?

**Comment by BereZambrano** [comment]
I will add: "what kind of online discussions do you know?" in order to identify different needs.

**Comment by BereZambrano** [comment]
I think we need to categorized something, whether is people, topics, kinds of discussions or whatever

**Comment by abhicodebase** [comment]
1. Can there be scenarios , where individual user / organization , might NOT want to summarise the discussions , espc in shorter duration . Issue  #62 
2. A bit academic perspective , but models like TAM , Extended TAM, TOE and DOI etc can also be used to explore the factor influencing the adaption of Wikum tool , by individuals and organizations.

**Comment by RamlAyadi** [comment]
1. YES! it can be so much other users scenarios (people might just read/have a quick an lisible overview of one discussions/ people don't want to summarize or lebel or tag or colouring ). A design approach perspective must begin bu **mapping Vikum** (aim/essential functions) <img src="https://github.com/Switch-Mexico/Switch-GUI/blob/master/public/imgs/screenshots/dashboard_00.png" alt="Screenshot 1" height="200px"/>
