### ISSUE TITLE
Allow to import discussion threads from Decide Madrid

### ISSUE THREAD

**Issue by elaragon** [amyxzhang/wikum#88]
### Issue 

As a developer who is going to collaborate in the improvement of WIKUM source code, I found that WIKUM

1. is limited to specific online discussion platforms (e.g. Reddit, Wikipedia), and
2. does not include some popular citizen participation platforms like Decide Madrid

### Proposal

To extend WIKUM to allow to import discussion threads from Decide Madrid

### Outcome

An extended version of the correspondig python scripts

### Engagement
Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by amyxzhang** [comment]
@elaragon commented elsewhere "I agree, data from discussions in debates and proposals are accesible via the GraphQL API: https://github.com/amiedes/consul/blob/1754-api-docs/doc/api/api_es.md"

**Comment by amyxzhang** [comment]
Closing this issue!
