### ISSUE TITLE
Missing Code Documentation

### ISSUE THREAD

**Issue by alexter42** [amyxzhang/wikum#90]
This issue is under consideration for the creation of WIKUM documentation.
(Texto en español abajo)
### Issue 

As a developer who is going to collaborate in the improvement of  the WIKUM source code, I find  hard to understand the structure of the project at a first glimpse. The deeper you dive into the  folders, the hardest it becomes.

### Proposal

I propose to create:

* A **README.md** file for each folder inside the project.

 ### Engagement
Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

--------------------------------------------------------------------------------------------

### Asunto

Como programador encuentro difícil comenzar a colaborar en el proyecto, pues existen muchas carpetas y echando un primer vistazo no obtengo mucha información acerca de lo que cada carpeta contiene.

### Propuesta

Propongo:

* Elaborar un archivo tipo README.md para cada folder que se encuentra dentro del proyecto.

**Comment by amyxzhang** [comment]
Example of standard main-repo README I've used before: https://github.com/RichardLitt/standard-readme

**Comment by alexter42** [comment]
Perfect, I'll follow those rules.

**Comment by amyxzhang** [comment]
Pull request #104 was merged which improved the repo-wide README.

**Comment by amyxzhang** [comment]
Marking this as closed (since we updated it in the KanBan).
