### ISSUE TITLE
Automatic generation of tags

### ISSUE THREAD

**Issue by julioremo** [amyxzhang/wikum#91]
### Issue

1. Multiple users may submit competing summaries to the same comment.
2. Multiple subthreads may discuss the same thing.

How to link this information?

### Proposal

I propose using tags to link different comments, and automatically generating tags in the background to create underlying links between different threads.

~~1. Rank alternative summaries according to:
     1. how they entail the text/tags that they're summarising
     2. the user influence rank
     3. up- and down-voting by the crowd (per comment)
2. Choose **one** alternative, indicate the presence of alternatives.
3. Automatically suggest the presence of similar threads + merge them when there's enough support/semantic similarity.~~

1. Automatically generate tags for every comment.

### Outcome

~~1. Generate tag suggestions per comment/(sub)thread
2. Generate suggestions of similar threads
3. A **Merge this thread?** button, or
4. A tree view that includes links among branches~~

A ranked list of keywords per comment.

### Future

Brainstorm with UX the possible uses / display / hiding of the automatic tags:

* As 'latent' (hidden) tags?
* As hidden links in the visualisation of the thread?

Also UX: give the user a strong suggestion to tag comments and summaries.

**Comment by amyxzhang** [comment]
Alternative is to keep it as it is (wiki-style) and add features to encourage more neutral/more complete summarization of the 1 summary (like wikipedia, which has high standards for edits).

**Comment by abhicodebase** [comment]
Can the tags in final summary , be used as some kind of parameter to validate the efficiency of entire summarization process. For e.g If the final summary has some tags , tags that other wise rarely appear in most of lower level summaries / comments , it might imply something unnatural .

**Comment by amyxzhang** [comment]
Whoohoo this is done!

Minor todos: 
- fix tags that are dark colored so that text is white. 
- clicking on a tag should populate the text bar. 
- script should delete all suggestions when repopulating suggested tags.
- Allow multiple tags in text bar using commas.
