### ISSUE TITLE
Effect of Trolls /  Attackers on Wikum Summarization 

### ISSUE THREAD

**Issue by abhicodebase** [amyxzhang/wikum#95]
Issue

As a developer who is going to collaborate in the improvement of WIKUM source code, I found that in WIKUM

effect of Trolls /  Attackers on Wikum Summarization quality needs to be explored . Different scenarios / domains ? 

Proposal

To study the impact of  presence of Trolls /  Attackers on Wikum Summarization quality .

Outcome

To answer the question how trolls / attackers might be able to effect the summarization quality . 

Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by amyxzhang** [comment]
Alternative but related: finding bad comments in the discussion to suggest for hiding.

**Comment by amyxzhang** [comment]
For attacker summarizers: some features include giving ability to the "owner" of the wikum to block a bad user from editing.

Another feature could be to allow the owner to "lock" a particular summary so no edits are allowed if there have been many back-and-forth edit wars.

**Comment by amyxzhang** [comment]
The brainstorm around this is done!

**Comment by abhicodebase** [comment]
The final outcome to be used for further action has been documented at - https://docs.google.com/document/d/1efPIBzNCIhPYYlmqIMoDIyo2GT9crQXWV6thK9dw_Jc/edit?usp=sharing
